### PR TITLE
Added http header properties for applying to file loaders

### PR DESCRIPTION
**Pull request by hawkzey**
Pretty straight forward pass through for Http headers so that they can be used in the fetch requests.

closes: #81

### CODE REVIEW

**Comment by Synthetium** [comment]
Nice man! This is super useful.

**Comment by codersmatter** [comment]
Any indication when this pull request will be added to master.  I've started using the component but need the http header properties.  Thanks in advance for all your good work!

**Comment by ximenean** [comment]
Why was this PR closed? I'd also like to see this added

**Comment by hawkzey** [comment]
@ximenean I think this package is not maintained.

**Comment by white-spirit** [comment]
sad, so sad

**Comment by ximenean** [comment]
@hawkzey thanks. What a shame.

**Pull request closed without merging**
